Refactoring getFileStatus Call
ABFSDriver/AbfsHadoop pull request #82
Opened 2023-07-18 10:39 UTC by sreeb-msft

This PR refactors getFileStatus call in abfsStore by breaking it down into another separate function - getPathProperty - that deals with the part for getting property of the current path. This helps in reducing number of server calls made in the scenarios where only the property of the blob/part is sufficient and the subsequent list call does not have to be made.

2023-07-18 11:41 UTC, saxenapranav requested changes
Good with code change. Nice!
Lets add tests for it please.

2023-07-18 12:01 UTC, anmolanmol1234 commented on hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
> +    AbfsPerfInfo perfInfo = startTracking("getFileStatus", "undetermined");
change name from getFileStatus to getPathProperty ?

2023-07-19 04:47 UTC, anujmodi2021 commented on hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
> +    AbfsPerfInfo perfInfo = startTracking("getFileStatus", "undetermined");
Actually this I suppose is to track the filesystem calls and should remain under getFileStatus only.
Reason being this function can be called from other File system calls like create and mkdir.

2023-07-25 03:39 UTC, saxenapranav requested changes
Tests look good.
Lets have assumptions that these test runs only on blob endpoint (prefixMode==BLOB).
Few suggestions as comments.

2023-07-25 03:39 UTC, saxenapranav commented on hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemListStatus.java
> +    Mockito.doReturn(client).when(store).getClient();
Lets do `store.setClient(client);`

2023-07-25 03:39 UTC, saxenapranav commented on hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemFileStatus.java
> +    fs.getFileStatus(new Path("/testGetPathProperty"));
Lets assert response's fileStatus show its is directory.

2023-07-25 03:39 UTC, saxenapranav commented on hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemFileStatus.java
> +    fs.getFileStatus(new Path("/testImplicitDirectory"));
Lets assert response's fileStatus show its is directory.

2023-07-25 03:40 UTC, saxenapranav commented on hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemListStatus.java
> +    Mockito.doReturn(client).when(store).getClient();
We can remove the change where client is replaced with getClient().

2023-07-25 06:10 UTC, anmolanmol1234 commented on hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
> +    AbfsPerfInfo perfInfo = startTracking("getFileStatus", "undetermined");
If that is the case should be added at line 2057

2023-07-25 08:14 UTC, saxenapranav approved these changes
LGTM! Thanks for taking the comments.

2023-07-25 10:46 UTC, snvijaya approved these changes
Inline to Anmol's comment. Nothing more from me. 
+1

2023-07-25 19:05 UTC, anmolanmol1234 approved these changes

2023-07-26 13:26 UTC, merged