Refactor Directory Check
ABFSDriver/AbfsHadoop pull request #87
Opened 2023-07-25 11:11 UTC by sreeb-msft

Reducing redundant code and using getPathProperty for checking parent chain of given path for determining whether directory or not. 

This also updates the user agents.

2023-07-26 04:23 UTC, saxenapranav requested changes

2023-07-26 04:23 UTC, saxenapranav commented on hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
> +    if (isDirectory) {
if its a file, we should throw 409 as per exisiting code.

2023-07-26 04:23 UTC, saxenapranav commented on hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
> +      if (isDirectory) {
same as above for 409.

2023-07-26 04:23 UTC, saxenapranav commented on hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemMkDir.java
> +    Mockito.verify(store, Mockito.atLeast(1)).tryGetPathProperty(Mockito.any(Path.class),
lets have Mockito.times()? I think it should invoke only once.

2023-07-27 04:50 UTC, anujmodi2021 commented on hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azurebfs/AzureBlobFileSystemStore.java
> +   * Method to make a call to get path property based on various configs-
We should specify in comments that this function will work only for explicit paths (files/directories).

2023-07-27 07:35 UTC, anmolanmol1234 approved these changes

2023-07-27 07:35 UTC, anujmodi2021 approved these changes
LGTM
Thanks for taking changes.

2023-07-27 08:02 UTC, saxenapranav requested changes
Since, 409 change was missed -> tests would not be there. Can you please add. If already kindly cite the tests (if yes, why they didn't pick 409 before).

Good with the code. Great code!

2023-07-27 08:02 UTC, saxenapranav commented on hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemMkDir.java
> +    Mockito.verify(testClient, Mockito.times(3)).getBlobProperty(Mockito.any(Path.class),
Hope that ingress,, mkdir swtiches tested?

2023-07-27 09:48 UTC, saxenapranav approved these changes
Great code. Thanks for taking suggestions.

2023-07-27 10:06 UTC, merged

2023-07-31 04:32 UTC, anmolanmol1234 commented on hadoop-tools/hadoop-azure/src/test/java/org/apache/hadoop/fs/azurebfs/ITestAzureBlobFileSystemMkDir.java
> +    AzureBlobFileSystem fs = Mockito.spy(getFileSystem());
No blob prefix check added